name: environment_template
channels:
  - conda-forge
  - opensim-org
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - coverage=7.11.1
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - glib=2.86.1
  - glib-tools=2.86.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - harfbuzz=12.2.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - ipykernel=6.31.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.5
  - libdeflate=1.25
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.1
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libtiff=4.7.1
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.2.1
  - mkl=2025.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=1.25.2
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - opensim=4.5.1
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.5
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - ply=3.11
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyside6=6.9.3
  - pytest=8.4.2
  - pytest-cov=7.0.0
  - pytest-qt=4.5.0
  - pytest-sugar=1.1.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.3
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - spyder-kernels=3.0.5
  - stack_data=0.6.3
  - tbb=2022.3.0
  - termcolor=3.2.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - altgraph==0.17.4
      - pefile==2023.2.7
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pywin32-ctypes==0.2.3
prefix: C:\Users\Scott\miniconda3\envs\environment_template
